### PR TITLE
Cross-compilation for MicroPython 1.12

### PR DESCRIPTION
**Pull request by poesel**
I've bumped mpy-cross to 1.12 because vanilla MicroPython is at 1.12 now, which is what I am using.

### CODE REVIEW

**Comment by poesel** [comment]
Hmm, two problems:
Make is missing the definition for MPY_VERSION and MPY_TARGET
I can set:
MPY_VERSION = 1.12 but where is the 'right' place for that?
But for MPY_TARGET 'pycom' works but not 'native'

`root@Calvin:/home/markus/GitHub/terkin-datalogger# make mpy-compile
[INFO]    Ahead-of-time compiling to .mpy native
[INFO]    Populating folder "lib-mpy-1.12-native"
make[1]: Entering directory '/mnt/c/Users/Markus/Documents/GitHub/terkin-datalogger'
PYTHONPATH=bin/mpy-cross/1.12 .venv2/bin/python ./bin/mpy_cross_all.py --target native --out lib-mpy-1.12-native lib
make[1]: Leaving directory '/mnt/c/Users/Markus/Documents/GitHub/terkin-datalogger'
make[1]: Entering directory '/mnt/c/Users/Markus/Documents/GitHub/terkin-datalogger'
PYTHONPATH=bin/mpy-cross/1.12 .venv2/bin/python ./bin/mpy_cross_all.py --target native --out lib-mpy-1.12-native/terkin terkin
ERROR: Invoking "mpy_cross.run()" failed
ERROR: The command was: /mnt/c/Users/Markus/Documents/GitHub/terkin-datalogger/bin/mpy-cross/1.12/mpy_cross/mpy-cross -v -v -X emit=native -s telemetry.py terkin/telemetry.py -o lib-mpy-1.12-native/terkin/telemetry.mpy
()
('STDOUT:\n', u'')
('STDERR:\n', u"mpy-cross: ../py/emitnative.c:2718: emit_native_raise_varargs: Assertion `n_args == 1' failed.\n")
Traceback (most recent call last):
  File "./bin/mpy_cross_all.py", line 103, in <module>
    run()
  File "./bin/mpy_cross_all.py", line 99, in run
    invoke_mpy_cross(mpy_cross_args)
  File "./bin/mpy_cross_all.py", line 63, in invoke_mpy_cross
    raise RuntimeError('Invoking "mpy_cross.run()" failed')
RuntimeError: Invoking "mpy_cross.run()" failed
make[1]: *** [tools/micropython.mk:102: mpy-cross] Error 1
make[1]: Leaving directory '/mnt/c/Users/Markus/Documents/GitHub/terkin-datalogger'
make: *** [Makefile:132: mpy-compile] Error 2`

**Comment by amotl** [comment]
Thanks!

The designated command for the most recent Pycom firmware is
```
make recycle-ng MPY_CROSS=true MPY_TARGET=pycom MPY_VERSION=1.11
```

Please keep the mpy-cross 1.11 version as we need it for bytecode-compilation for the Pycom firmware.

**Comment by amotl** [comment]
So, the appropriate command for vanilla MicroPython could be
```
export MCU_PORT=/dev/ttyS3
make install-ng MPY_CROSS=true MPY_TARGET=bytecode MPY_VERSION=1.12
```

**Comment by poesel** [comment]
I have a problem importing the compiled mpy files. It seems uPy ignores them,
I have deliberately taken away the /terkin sys.path to force uPy to use the mpy files in /lib...
This was the result:

> [boot.py] INFO: Python module search path is: ['', '/lib']
> [boot.py] INFO: Universal MicroPython Application Loader (umal)
> [umal]    INFO: Python module search path is: ['/lib-mpy-112-bytecode', '', '/lib']
> [main.py] INFO: Loading settings
> [main.py] INFO: Starting logging
> Traceback (most recent call last):
>   File "main.py", line 21, in <module>
>   File "logging.py", line 7, in <module>
> ImportError: no module named 'logging'
> MicroPython v1.12 on 2019-12-20; ESP32 module (spiram) with ESP32
> Type "help()" for more information.

Another problem: the pycom module in VSC cannot handle dots ('.') in directory names. So I had to rename 'lib-mpy-1.12-bytecode' to 'lib-mpy-112-bytecode'.

However I can import mpy files that are in the top directory. Wasn't there an issue with mpy files and subdirectories?

**Comment by amotl** [comment]
Hmmm, I believe it worked for me when trying this on a Pyboard. It looks like we have to investigate further.

**Comment by poesel** [comment]
I checked if it is possible to import .mpy's from sub- and subsub directories. It works. No bug here.
Still I don't know why it fails to import.

Other questions: 
Why is 'dist-packages' only compiled for target 'pycom'?
Shouldn't there be the option '-march=xtensa' for the pycom & ESP boards?

**Comment by amotl** [comment]
> I checked if it is possible to import .mpy's from sub- and subsub directories. It works. No bug here.

Good to hear it works.

> Still I don't know why it fails to import.

So importing works but then it fails?

> Why is 'dist-packages' only compiled for target 'pycom'?

Is it? Maybe some wiring is wrong within the `Makefile`?

> Shouldn't there be the option '-march=xtensa' for the pycom & ESP boards?

According to `bin/mpy-cross/1.11/mpy_cross/mpy-cross --help`, the `-march` option is only used when emitting native code.
```
-march=<arch> : set architecture for native emitter; x86, x64, armv6, armv7m, xtensa
```

**Comment by amotl** [comment]
With 7f2111b, `dist-packages` is compiled unconditionally and `mpy-cross==1.12` is installed side-by-side with version 1.11.

So, this command populates the `lib-mpy-1.12-bytecode` folder successfully with all of the bytecode.
```
make mpy-compile MPY_CROSS=true MPY_TARGET=bytecode MPY_VERSION=1.12
```

**Comment by poesel** [comment]
> Is it? Maybe some wiring is wrong within the Makefile?

Thats the Makefile:

        @if test "${MPY_TARGET}" = "pycom"; then \
                $(MAKE) mpy-cross what="--out $(mpy_path) dist-packages"; \
        fi
        @$(MAKE) mpy-cross what="--out $(mpy_path) lib"
        @$(MAKE) mpy-cross what="--out $(mpy_path)/terkin terkin"

And that was the cause of my import problem. I tried to force reading the mpy files and removed /terkin and /dist-packages from sys.path. Since the packages weren't compiled the couldn't be imported... d'oh!

I've changed the Makefile and removed the 'if pycom...'.
mpy-compile will now populate the /lib-... folder with the content of /dist-packages. Thats a bit ugly but seems to work.
Shaved of 6 seconds of boot time (from 22 to 16 until the first line of the logger comes up). Honestly I had hoped for more. Looks like it is necessary to freeze.

**Comment by thiasB** [comment]
Also, [tools/upload-mpy.rshell](https://github.com/hiveeyes/terkin-datalogger/blob/0acadbb/tools/upload-mpy.rshell) is still hard wires the`lib-mpy-1.11-pycom` folder and needs dynamic version handling or version specific `.rshell` files, respectively.

**Comment by amotl** [comment]
> `tools/upload-mpy.rshell` still hard-wires the `lib-mpy-1.11-pycom` folder.

So true, thanks for mentioning! Are you also working with vanilla MicroPython, Matthias? @poesel decided to opt-in for compile-only and will transfer the files using VSCode.

**Comment by amotl** [comment]
Dear @poesel,

while I like the `config.mk` approach for having a shortcut in there, will it be possible to still pass arguments on the command line?

While the main target is still Pycom,
```
make mpy-compile MPY_CROSS=true MPY_TARGET=pycom MPY_VERSION=1.11
```
I will be happy to support all platforms equally.

I am just thinking about the appropriate implementation here which doesn't add bias into one or another direction. A while ago, I was planning to rewrite the whole build driver using Python which would give us way more flexibility on many levels. Right know, we are probably stuck with the `Makefile`-based approach and all I want to achieve here is at least some convenience/elegance without disrupting the existing approach too much.

Thanks for listening and with kind regards,
Andreas.

**Comment by poesel** [comment]
> while I like the `config.mk` approach for having a shortcut in there, will it be possible to still pass arguments on the command line?

Since the include is in the Makefile I guess that anything in config.mk would overwrite parameters given on the command line.
But IIRC there is this '?=' syntax which only sets a variable if it is not set. Maybe thats the way to go?

**Comment by amotl** [comment]
> But IIRC there is this ?= assignment syntax which only sets a variable if it is not set. Maybe that's the way to go?

That would be awesome. Will you be able to test this detail if you find some minutes and eventually update the pull request afterwards?

**Comment by poesel** [comment]
That should be it if I didn't mess up with Git...

**Comment by amotl** [comment]
Can I ask you to add https://github.com/poesel/terkin-datalogger/pull/1 beforehand?

**Comment by poesel** [comment]
You have to be more explicit wrt Git with me :)
I was wondering to what I should be added to :D

**Comment by amotl** [comment]
Dear @poesel and @thiasB,

I have deliberately squashed these updates and integrated them through dbfa32d6. Thanks a bunch for your efforts!

With kind regards,
Andreas.

**Pull request closed without merging**
