### PR TITLE
Add docker-compose configuration for Hiveeyes backend

### PR DESCRIPTION
**Pull request by WSt89**
add hiveeyes-backend-docker-compose

### CODE REVIEW

**Comment by poesel** [comment]
First of all thank you for your contribution!

Here are my thoughts:

Maybe have a more discerning name for 'volumes' - 'dockervolumes'?

This directory should be in .gitignore else it would get committed.

Since there are various .conf and .ini files it may be a good idea to put them into a separate 'docker' directory to keep the amount of clutter in check.

The whole show uses 'make' to run things. So instead of a shell script we need a rule in make. Are you familiar with that? Maybe I can help a bit but I do not know much about it.

**Comment by WSt89** [comment]
I agree that moving docker related files into a dedicated folder would be better. I am familiar in using make but haven't created targets yet. However, I can try to integrate it.

**Comment by poesel** [comment]
Is this now ready to merge?

**Comment by amotl** [comment]
Dear @WSt89,

thanks a stack for your contribution and apologies for the very late reply. We only recently picked up work on this repository again.

I appreciate your setup very much and love to see the passion you poured into each detail in order to bundle the Hiveeyes backend stack into a concise configuration based on Docker, you even included PutsReq!

However, I feel it doesn't fit well into this repository and started thinking if https://github.com/daq-tools/kotori would be a better place. Nevertheless, I also rejected that idea.

The final outcome from my end was, that it would be definitively worth to **dedicate a separate repository to this, just boldly called `hiveeyes/hiveeyes-backend`**. What do you think about this?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Werner,

I will close this in favor of https://github.com/hiveeyes/hiveeyes-backend-docker and https://github.com/WSt89/hiveeyes-backend-docker-compose/pull/2.

Thanks again, this is a very valuable contribution!

With kind regards,
Andreas.

**Pull request closed without merging**
